### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by QingkaiLu** [snap-research/NeROIC#14]
Hi, thank you for sharing the code. Is the pre-trained model available? Thanks!

**Comment by zfkuang** [comment]
I don't have any pre-trained model on my site for now (it's on the old server), but I can train one and share it this week.

**Comment by QingkaiLu** [comment]
Thank you, Zhengfei. It would be great if you can provide a pre-trained model! Looking forward to it!

**Comment by zfkuang** [comment]
Hi,

Here's a model trained with the milk box dataset: https://drive.google.com/drive/folders/1haU2fURW9VcYryoiJGrALxVug5VN-S1l?usp=sharing

I only have 1 GPU for training now, so this model is slightly underfitting, but it generally looks fine.

**Comment by QingkaiLu** [comment]
Thank you, Zhengfei!
