### ISSUE TITLE
Question on Foreground Masks

### ISSUE THREAD

**Issue by jianweif** [snap-research/NeROIC#15]
The masks in provided data seem perfect. I am working on my own data and wondering if it can work with noisy foreground mask coming from a saliency detection model or it has to be perfect foreground mask. Thanks!

**Comment by zfkuang** [comment]
Good question! You can annotate the mask your self. Just make sure that the masks are always **bigger** than the object (i.e. contain the whole object), and don't contain much background pixels. Our model should be robust enough to handle it.
