### ISSUE TITLE
Add mesh preview every XX epoch?

### ISSUE THREAD

**Issue by Michaelwhite34** [snap-research/NeROIC#17]
For me training take hours, and I don't know if things go wrong before training ends.

**Comment by zfkuang** [comment]
there are two ways to check if things go right: First you can set the "verbose" param on, and it will let the program validate the model after every epoch. Second you can change the value of "i_video", this will let the program render a 360 video in every certain iterations. We don't provide code for mesh extraction, but you can refer to this issue: https://github.com/snap-research/NeROIC/issues/10
