### ISSUE TITLE
Segmentation masks

### ISSUE THREAD

**Issue by anna-debug** [snap-research/NeROIC#18]
Hi, what kind of a method can be used to get the black and white masks needed to run this on a custom dataset?

**Comment by kyleolsz** [comment]
For real objects (i.e., not synthetic 3D renderings for which you can just produce alpha masks), we've used online tools such as https://www.remove.bg/. It should give you a PNG image with an alpha channel that can be used for mask supervision. 

Implementation of other automatic foreground/background segmentation or semantic segmentation tools (e.g. Mask R-CNN), can be found on GitHub and should also work, but we've mostly used the aforementioned website with sufficient results.

If those don't work or the results need some manual adjustment to add/remove regions, utilities like the lasso tools in Photoshop or other free image editing apps can also be used.

However, if there are only relatively minor inaccuracies around the borders, e.g. if it's a little too large and inconsistent between images, our method should still be robust enough to produce reasonable results.
