### ISSUE TITLE
how to run it with a custom single image

### ISSUE THREAD

**Issue by igorvazz** [snap-research/NeROIC#19]
Hi, is there some documentation on how to run/train this model using a single image from an object?

**Comment by kyleolsz** [comment]
I'm a little unclear what you're asking. Are you trying to perform decomposition from a single image? Our approach is intended for cases where there are multiple images of the target object that can be used to learn its decomposition.

To get a reasonable estimate of the geometry, lighting environments, and material properties, you'd need several images to disambiguate and decompose these elements from one another. With just a single image, you'd need some prior knowledge of these parameters for the given object or object category to make a reasonable inference as to these properties.

**Comment by igorvazz** [comment]
thanks for answering @kyleolsz, you were faster than me, as I've realized the answer to my question only after reading the paper section about the COLMAP usage.
