### ISSUE TITLE
Can NeROIC run on CPU？

### ISSUE THREAD

**Issue by awenhaowenchao** [snap-research/NeROIC#21]
I modifid train.py\ generate_normal.py\dataset.py to cpu device type。
Then I execute code `python train.py \
--config configs/milkbox_geometry.yaml \
--datadir ./data/milkbox_dataset`.
But there not generate 'epoch=29.ckpt' file

**Comment by zfkuang** [comment]
Hi,

As our model requires 20-30 hours of training with GPUs, I would say running NeROIC on CPU is not suggested.

Zhengfei

**Comment by awenhaowenchao** [comment]
thx
