### ISSUE TITLE
Is there any way to export 3D models to run on general 3D software

### ISSUE THREAD

**Issue by liuguicen** [snap-research/NeROIC#24]
Hello， I came here from the Instant ngp issues “export of 3D model is not clear ...". Is there any way to export clear 3D models to run on general 3D software in this paper?

**Comment by Bitfultea** [comment]
it remains a tricky problem this stage as nerf was trying to render a 3d object without the actual 3d model. The nvidia Instant npg use their reverse rendering lib which is what I found the most feasible way to construct 3d model from nerf. corret me if im warong

**Comment by liuguicen** [comment]
OK, thanks

**Comment by wagnerponciano** [comment]
So there is no 3d object in fact it's just for lighting and rendering? In case you can't get obj or stl from it?
