### ISSUE TITLE
Can you tell us when the code will be open sourced,waiting for a very very long time,really looking forward to your results

### ISSUE THREAD

**Issue by Evilom** [snap-research/NeROIC#5]
Can you tell us when the code will be open sourced,waiting for a very very long time,really looking forward to your results

**Comment by MohamedAliRashad** [comment]
same here

**Comment by koktavy** [comment]
Just learned about this today after getting [Instant NGP](https://github.com/NVlabs/instant-ngp) up and running. Can't wait!
