### ISSUE TITLE
when will the code be released?

### ISSUE THREAD

**Issue by Bitfultea** [snap-research/NeROIC#6]
Have been patiently waiting for months, is anyone working on this repo?

**Comment by TheMcSebi** [comment]
also curious, what "soon" means :)

**Comment by hailangWu-Aval** [comment]
"soon" means about six month to a year,  abort following~

**Comment by HQgDJ** [comment]
Also means 1 decade right??

**Comment by denysza** [comment]
I am waiting about 4 months

**Comment by hemath1001** [comment]
Looking forward to it too~~~~

**Comment by zfkuang** [comment]
Thanks for the waiting! We will release our code before the end of July :)

**Comment by NowLoadY** [comment]
so I will be ready to build 3d model of my action figures!

**Comment by denysza** [comment]
> Thanks for the waiting! We will release our code before the end of July :)

Where can I find code?

**Comment by pwais** [comment]
WOOT!
