### ISSUE TITLE
data missing pose file

### ISSUE THREAD

**Issue by flynnamy** [snap-research/NeROIC#9]
The figure dataset missing poses_bounds.npy,please check and share it.Thanks! @formyfamily

**Comment by zfkuang** [comment]
Thanks for pointing this out! Looks like I somehow deleted them accidentally. It's uploaded now.

**Comment by flynnamy** [comment]
Hi，the numbers and the size of masks is not corresponding to the images about figure dataset. Please check and share it.Thanks! @formyfamily

**Comment by zfkuang** [comment]
seems some mask files are missing too, uploaded them. 

No worry about mask sizes, they will get resized in the dataloader.
